import spriteData from './sprite-data.json'
import { asset } from './assets'

export type Flavor = string

export interface SpriteMeta {
  width: number
  height: number
  /** Centroid of the alpha mask, in sprite pixels. The anchor to place by. */
  cx: number
  cy: number
  /** Major/minor axes of the alpha mask - the pizza's apparent diameter. */
  major: number
  minor: number
}

interface SpriteData {
  poseCount: number
  /** Flavours with a complete set of poses built, discovered from disk. */
  flavours: string[]
  sprites: Record<string, SpriteMeta>
}

const data = spriteData as SpriteData

export const POSE_COUNT = data.poseCount

/**
 * The order the menu board on the wall lists them in.
 *
 * The flavours themselves are discovered from the sprites on disk, which comes
 * back alphabetical - so the site opened on diavola and read down the menu in
 * an order that matched nothing in the room. The chalkboard behind the counter
 * is in the photograph, a visitor can read it, and it is the menu. Anything
 * generated later that is not on the board follows on behind.
 */
const BOARD = ['margherita', 'pepperoni', 'diavola', 'veggie', 'formaggi', 'speciale']

const boardRank = (f: string) => {
  const i = BOARD.indexOf(f)
  return i < 0 ? BOARD.length : i
}

export const FLAVORS: Flavor[] = [...data.flavours].sort(
  (a, b) => boardRank(a) - boardRank(b) || a.localeCompare(b)
)

/**
 * What the buttons and the readout call each flavour.
 *
 * Kept here rather than in the sprite data because a slug is a filename, not a
 * name: "formaggi" has to read as "4 FORMAGGI". Anything without an entry falls
 * back to its slug uppercased, so a newly generated flavour appears in the UI
 * immediately and only needs an entry here if its name is not just the slug.
 */
const LABELS: Record<string, string> = {
  formaggi: '4 FORMAGGI',
  speciale: 'PIZZA SPECIALE',
}

export const labelFor = (flavour: Flavor) => LABELS[flavour] ?? flavour.toUpperCase()

/**
 * The nine poses of one flavour, in playback order: flat on the peel, up
 * through the tumble, back down to flat.
 *
 * Every flavour is the same nine rotations - the sprites were generated by
 * repainting the toppings onto these exact poses - so any flavour can be
 * substituted for any other at any point in the toss and the pizza carries on
 * turning as though nothing happened. That is what makes the number of sprites
 * grow with the number of flavours rather than with the number of *pairs* of
 * them.
 */
export const posesFor = (flavour: Flavor) =>
  Array.from({ length: POSE_COUNT }, (_, i) => {
    const name = `pizza-${flavour}-${i + 1}`
    return { src: asset(`sprites/${name}.webp`), meta: data.sprites[name] }
  })

export const PEEL = { src: asset('sprites/peel.webp'), meta: data.sprites.peel }

/** Native size of the background plate. All scene coordinates are in its space. */
export const PLATE = { src: asset('plate.webp'), width: 1672, height: 941 }

/**
 * Where the peel's blade sits inside its own sprite, measured off the artwork.
 * The sprite's alpha moments are no use for this one: the long handle drags the
 * centroid down out of the blade and inflates the major axis, so the blade is
 * described directly instead.
 */
const PEEL_BLADE = { cx: 373, cy: 168, width: 725 }

/** Pizza centroid, in plate pixels, when it is resting on the peel. */
export const REST = { x: 838, y: 700 }

/** Apparent diameter of the pizza at rest, in plate pixels. */
export const PIZZA_DIAMETER = 500

/**
 * Peel blade width relative to the pizza, and how far below it the blade sits.
 *
 * Only just wider than the pizza. The blade is a big pale disc and the handle
 * runs off the bottom of the frame, so any more than this and the tool reads as
 * the subject instead of the thing the pizza is sitting on.
 */
const PEEL_WIDTH_RATIO = 1.04
const PEEL_DROP = 18

/** How far the centroid climbs at the top of the toss, in plate pixels. */
const APEX_RISE = 470
/** Extra scale at the apex - the pizza is nearer the camera up there. */
const APEX_GROWTH = 0.17
/** Lateral sway through the toss. */
const DRIFT_X = 30
/** How much the pizza flattens as it pushes off and as it lands. */
const SQUASH = 0.07

/**
 * Point in a toss where the pizza stops being the old flavour and becomes the
 * new one.
 *
 * Not the apex, which is the obvious guess and the wrong one: `p` is tweened
 * linearly and the height follows a parabola, so vertical speed is *zero* at
 * the top. The pizza hangs there, at its largest, moving slowest - the most
 * visible moment in the whole toss, and the worst possible place to change
 * something.
 *
 * 0.375 is pose 4, on the way up: near enough to the top to read as the turn,
 * still travelling fast enough to carry motion blur, and the second-most
 * foreshortened pose in the set, so the least amount of topping is facing the
 * camera when it changes. Worth re-tuning by eye if the poses are ever
 * regenerated - the honest fix would be a genuinely edge-on pose to swap on.
 */
const SWAP_AT = 0.375

/** Contact shadow on the counter. */
const SHADOW = { drop: 34, width: 0.94, squash: 0.2, alpha: 0.46 }

/**
 * Smooth 0 -> 1 -> 0 over [a, b], zero outside it, peaking at `crest` of the
 * way through - a snap up and a slower fall back, rather than a symmetric swell.
 */
const snap = (v: number, a: number, b: number, crest: number) => {
  if (v <= a || v >= b) return 0
  const t = (v - a) / (b - a)
  const u = t < crest ? t / crest / 2 : 0.5 + (t - crest) / (1 - crest) / 2
  return Math.sin(Math.PI * u)
}

export interface Pose {
  /** Pizza centroid in plate coordinates. */
  x: number
  y: number
  /** Multiplier on PIZZA_DIAMETER. */
  scale: number
  /** Extra vertical squash, 1 = none. Applied about the centroid. */
  squash: number
  /** Which of the nine poses to draw. */
  index: number
  shadow: { x: number; y: number; rx: number; ry: number; alpha: number }
  peel: { x: number; y: number; width: number; rotation: number }
}

/**
 * The whole scene at timeline position `p`.
 *
 * The timeline is cyclic: every whole number is a pizza sitting on the peel,
 * and each unit interval is one complete toss. Choosing a flavour advances `p`
 * by one, so tosses chain - press four flavours quickly and the pizza keeps
 * tumbling through all four rather than reversing back down a two-ended track.
 *
 * Within a toss, height follows 4t(1-t) - a real parabola - and `p` is tweened
 * linearly in time, so the pizza leaves fast, hangs at the top and accelerates
 * back down on its own. Putting the easing in the arc rather than in the tween
 * also means the rotation advances at a constant rate, which is what a tumbling
 * object actually does.
 */
export function poseAt(p: number): Pose {
  const t = p - Math.floor(p)
  const lift = 4 * t * (1 - t)

  // Nearest pose, drawn on its own - no cross-fade between poses.
  //
  // Blending two poses cannot keep the pizza opaque. Weighting them to sum to
  // 1 leaves the middle of the dissolve see-through; laying the next pose over
  // a solid previous one keeps it opaque but leaves the old crust showing
  // around the edges. Since position, scale and blur are all continuous, the
  // rotation is the only thing a blend would smooth, and snapping it - the way
  // any sprite animation does - is worth far more than it costs.
  //
  // The modulo is what closes the cycle: the last step of a toss wraps back to
  // pose 1, so a landed pizza is always sitting in pose 1 whether it just
  // arrived or has been there all along. Without it the pizza would settle on
  // pose 9 and then silently switch to pose 1 the instant it came to rest -
  // a change of shape at the one moment nothing else is moving to hide it.
  const index = Math.round(t * POSE_COUNT) % POSE_COUNT

  const scale = 1 + APEX_GROWTH * lift
  const x = REST.x + DRIFT_X * Math.sin(Math.PI * t)
  const y = REST.y - APEX_RISE * lift

  // The peel flicks up hard as the pizza leaves and again to meet it coming
  // down, so the toss looks caused rather than coincidental.
  const launch = snap(t, 0, 0.34, 0.22)
  const catchIt = snap(t, 0.66, 1, 0.78)
  const peelWidth = PIZZA_DIAMETER * PEEL_WIDTH_RATIO

  return {
    x,
    y,
    scale,
    squash: 1 - SQUASH * (launch + catchIt),
    index,
    shadow: {
      x,
      y: REST.y + SHADOW.drop,
      rx: PIZZA_DIAMETER * 0.5 * SHADOW.width * (1 - 0.36 * lift),
      ry: PIZZA_DIAMETER * 0.5 * SHADOW.width * SHADOW.squash * (1 - 0.36 * lift),
      alpha: SHADOW.alpha * (1 - 0.72 * lift),
    },
    peel: {
      x: REST.x,
      y: REST.y + PEEL_DROP - 54 * launch - 30 * catchIt,
      width: peelWidth,
      rotation: -0.15 * launch - 0.09 * catchIt,
    },
  }
}

/**
 * A running order of what the pizza is at each landing.
 *
 * `plan[n]` is the flavour resting on the peel at timeline position `n`, so a
 * toss from `n` to `n+1` turns `plan[n]` into `plan[n+1]`. Choosing a flavour
 * appends to it; nothing is ever rewritten behind the pizza.
 */
export type Plan = Flavor[]

/** Which flavour is on screen at `p`, given the running order. */
export function flavorAt(p: number, plan: Plan): Flavor {
  const cycle = Math.floor(p)
  const t = p - cycle
  const landed = plan[Math.min(cycle, plan.length - 1)]
  if (t < SWAP_AT) return landed
  return plan[Math.min(cycle + 1, plan.length - 1)]
}

export { PEEL_BLADE, SWAP_AT }
